Silence deprecation error for openUrl
Summary:
A quick down-and-dirty fix for the inability to build in Xcode 8.3 because of the following error:
```
/Users/isaac/code/isaac-WDA/WebDriverAgentLib/Commands/FBSessionCommands.m:56:43: error: 'openURL:' is deprecated: first
      deprecated in iOS 10.0 - Please use openURL:options:completionHandler: instead [-Werror,-Wdeprecated-declarations]
  if (![[UIApplication sharedApplication] openURL:url]) {
                                          ^
In module 'XCTest' imported from /Users/isaac/code/isaac-WDA/PrivateHeaders/XCTest/XCUIApplication.h:7:
In module 'UIKit' imported from /Applications/Xcode-8.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCUIElement.h:8:
/Applications/Xcode-8.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:125:1: note:
      'openURL:' has been explicitly marked deprecated here
- (BOOL)openURL:(N
Closes https://github.com/facebook/WebDriverAgent/pull/532

Differential Revision: D4843239

Pulled By: marekcirkos

fbshipit-source-id: 1e7e6a4612beaa903bec35a5613d16c88e30c5b5